package com.blog.demo.dao;

import com.blog.demo.entity.ArticleLabel;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ArticleLabelMapper {
	//批量插入
	public void addArtLabels(@Param("ArLabels") List<ArticleLabel> ArLabels); 
	int deleteByLabelId(Integer labelId);
	int deleteByBlogId(Integer blogId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    int deleteByPrimaryKey(Integer articleLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    int insert(ArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    ArticleLabel selectByPrimaryKey(Integer articleLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    List<ArticleLabel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_label
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    int updateByPrimaryKey(ArticleLabel record);
}