package com.blog.demo.dao;

import com.blog.demo.entity.Comments;
import java.util.List;

public interface CommentsMapper {
	//根據文章Id刪除評論
	int deleteByarticleId(Integer articleId);
	List<Comments> selectByArticleId(Integer articleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    Comments selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    List<Comments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    int updateByPrimaryKey(Comments record);
}