package com.blog.demo.dao;

import com.blog.demo.entity.Role;
import java.util.List;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Jul 24 19:02:59 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Jul 24 19:02:59 CST 2020
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Jul 24 19:02:59 CST 2020
	 */
	Role selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Jul 24 19:02:59 CST 2020
	 */
	List<Role> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Jul 24 19:02:59 CST 2020
	 */
	int updateByPrimaryKey(Role record);
}