package com.blog.demo.dao;

import com.blog.demo.entity.Role;
import com.blog.demo.entity.SysUsers;

import java.util.List;

public interface SysUsersMapper {
	SysUsers loadUserByUsername(String username);
	List<Role> getUserRolesByUid(Integer id); 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Fri Jul 24 19:02:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Fri Jul 24 19:02:42 CST 2020
     */
    int insert(SysUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Fri Jul 24 19:02:42 CST 2020
     */
    SysUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Fri Jul 24 19:02:42 CST 2020
     */
    List<SysUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Fri Jul 24 19:02:42 CST 2020
     */
    int updateByPrimaryKey(SysUsers record);
}