package com.blog.demo.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Articles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.sys_user_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private Integer sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_title
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.sort_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_date
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date articleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_ cover
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private String articleCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_content
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_id
     *
     * @return the value of articles.article_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    private String publishStatus;
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_id
     *
     * @param articleId the value for articles.article_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.sys_user_id
     *
     * @return the value of articles.sys_user_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.sys_user_id
     *
     * @param sysUserId the value for articles.sys_user_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_title
     *
     * @return the value of articles.article_title
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_title
     *
     * @param articleTitle the value for articles.article_title
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.sort_id
     *
     * @return the value of articles.sort_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.sort_id
     *
     * @param sortId the value for articles.sort_id
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_date
     *
     * @return the value of articles.article_date
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public Date getArticleDate() {
        return articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_date
     *
     * @param articleDate the value for articles.article_date
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setArticleDate(Date articleDate) {
        this.articleDate = articleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_ cover
     *
     * @return the value of articles.article_ cover
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_ cover
     *
     * @param articleCover the value for articles.article_ cover
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_content
     *
     * @return the value of articles.article_content
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_content
     *
     * @param articleContent the value for articles.article_content
     *
     * @mbg.generated Sat Jun 27 15:50:42 CST 2020
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

	public String getPublishStatus() {
		return publishStatus;
	}

	public void setPublishStatus(String publishStatus) {
		this.publishStatus = publishStatus;
	}
}