package com.blog.demo.entity;

public class ArticleLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.article_label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    private Integer articleLabelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.article_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    private Integer labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.article_label_id
     *
     * @return the value of article_label.article_label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public Integer getArticleLabelId() {
        return articleLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.article_label_id
     *
     * @param articleLabelId the value for article_label.article_label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public void setArticleLabelId(Integer articleLabelId) {
        this.articleLabelId = articleLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.article_id
     *
     * @return the value of article_label.article_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.article_id
     *
     * @param articleId the value for article_label.article_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.label_id
     *
     * @return the value of article_label.label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.label_id
     *
     * @param labelId the value for article_label.label_id
     *
     * @mbg.generated Fri Jul 17 10:25:12 CST 2020
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

	public ArticleLabel(Integer articleId, Integer labelId) {
		super();
		this.articleId = articleId;
		this.labelId = labelId;
	}
    
}