package com.blog.demo.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_user
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    private String commentUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_date
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date commentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_content
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_id
     *
     * @return the value of comments.comment_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_id
     *
     * @param commentId the value for comments.comment_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_user
     *
     * @return the value of comments.comment_user
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public String getCommentUser() {
        return commentUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_user
     *
     * @param commentUser the value for comments.comment_user
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public void setCommentUser(String commentUser) {
        this.commentUser = commentUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param articleId the value for comments.article_id
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_date
     *
     * @return the value of comments.comment_date
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_date
     *
     * @param commentDate the value for comments.comment_date
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_content
     *
     * @return the value of comments.comment_content
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_content
     *
     * @param commentContent the value for comments.comment_content
     *
     * @mbg.generated Sun Jun 28 12:15:07 GMT+08:00 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
}