package com.blog.demo.entity;

public class Labels {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labels.label_id
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    private Integer labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labels.label_name
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    private String labelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labels.label_id
     *
     * @return the value of labels.label_id
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labels.label_id
     *
     * @param labelId the value for labels.label_id
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labels.label_name
     *
     * @return the value of labels.label_name
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labels.label_name
     *
     * @param labelName the value for labels.label_name
     *
     * @mbg.generated Fri Jul 17 10:23:53 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

	public Labels(String labelName) {
		super();
		this.labelName = labelName;
	}
	
    
}