package com.blog.demo.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_user
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    private String messageUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_data
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date messageData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_content
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    private String messageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_user
     *
     * @return the value of message.message_user
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public String getMessageUser() {
        return messageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_user
     *
     * @param messageUser the value for message.message_user
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public void setMessageUser(String messageUser) {
        this.messageUser = messageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_data
     *
     * @return the value of message.message_data
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public Date getMessageData() {
        return messageData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_data
     *
     * @param messageData the value for message.message_data
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public void setMessageData(Date messageData) {
        this.messageData = messageData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_content
     *
     * @return the value of message.message_content
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_content
     *
     * @param messageContent the value for message.message_content
     *
     * @mbg.generated Sun Jun 28 15:08:43 GMT+08:00 2020
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "Message [messageUser=" + messageUser + ", messageContent=" + messageContent + "]";
    }
}