package com.blog.demo.entity;

public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.user_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.role_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.id
	 * @return  the value of user_role.id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.id
	 * @param id  the value for user_role.id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.user_id
	 * @return  the value of user_role.user_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.user_id
	 * @param userId  the value for user_role.user_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.role_id
	 * @return  the value of user_role.role_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.role_id
	 * @param roleId  the value for user_role.role_id
	 * @mbg.generated  Fri Jul 24 19:03:31 CST 2020
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public UserRole(Integer userId, Integer roleId) {
		super();
		this.userId = userId;
		this.roleId = roleId;
	}
	
}